---
- name: Установка QT
  ansible.builtin.apt:
    name:
      - build-essential
      - qtcreator
      - mesa-common-dev
      - qt5-qmake
      - cmake
      - qt5-doc
      - qt5-doc-html
      - qtbase5-dev
      - qtbase5-dev-tools
      - qtbase5-doc
      - qtbase5-doc-html
      - qtbase5-examples
      - libqt5charts5-dev
      - qtcharts5-doc
      - qtcharts5-doc-html
      - qtcharts5-examples
    state: present
    update_cache: true

- name:
  apt:
    name:
      - language-pack-ru
      - language-pack-gnome-ru
      - language-pack-kde-ru
      - libreoffice-l10n-ru
      - libreoffice-help-ru
    state: present
    update_cache: yes


- name: Обновление языка
  shell: |
    sudo update-locale LANG=ru_RU.UTF-8

- name: Установка Snap
  ansible.builtin.apt:
    name: snapd
    state: present
    update_cache: true

- name: Установка Libre Office + Libre Base
  ansible.builtin.apt:
    name:
      - libreoffice
      - libreoffice-base
    state: present
    update_cache: true

- name: Установка VSCode
  community.general.snap:
    name: code
    state: present
    classic: true

- name: Установка Android-studio
  community.general.snap:
    name: android-studio
    state: present
    classic: true

# - name: Установка PyCharm
#   community.general.snap:
#     name: pycharm-community
#     state: present
#     classic: true

- name: Установка IntelijIDEA Community
  community.general.snap:
    name: intellij-idea-community
    state: present
    classic: true

- name: Установка GIMP
  ansible.builtin.apt:
    name:
      - gimp
      - gimp-plugin-registry
    state: present
    update_cache: true

- name: Установка Git
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: true

- name: Установка Htop
  ansible.builtin.apt:
    name: htop
    state: present
    update_cache: true

- name: Установка Traceroute
  ansible.builtin.apt:
    name: traceroute
    state: present
    update_cache: true

- name: Установка Python3
  ansible.builtin.apt:
    name:
      - python3-pip
    state: present
    update_cache: true

- name: Установка Octave
  ansible.builtin.apt:
    name: octave
    state: present
    update_cache: true

- name: Установка GNU Radio
  ansible.builtin.apt:
    name: gnuradio
    state: present
    update_cache: true

- name: Установка русской раскладки
  ansible.builtin.apt:
    name: language-pack-ru
    state: present
    update_cache: true

- name: Установка зависимостей для Spyder
  apt:
    name:
      - python3
      - python3-pip
      - python3-dev
      - python3-venv
      - libxcb-xinerama0  # Для графической части
    state: present
    update_cache: yes
- name: Установка Spyder через pip
  pip:
    name:
      - spyder
      - numpy
      - pandas
      - matplotlib
